version: '2'


services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 4000:3000
    volumes:
      - ./frontend:/app
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/phpmyadmin:/usr/share/nginx/html
      - ./nginx/ssl:/usr/share/nginx/ssl
    networks:
      - internal

networks:
  internal:
    driver: bridge
